package music;

/**
 * List of common chord names, independent of the root note.
 * 
 * @author Edward
 */
public enum ChordName
{
	MAJOR, MINOR, SEVEN, MINOR_SEVEN, MAJOR_SEVEN, MINOR_SHARP_SEVEN,
	SEVEN_FLAT_FIVE, SEVEN_SHARP_FIVE, HALF_DIMINISHED, SEVEN_FLAT_NINE,
	FLAT_FIVE, FIVE, SIX, MINOR_SIX, SIX_NINE, NINE, NINE_FLAT_FIVE,
	NINE_SHARP_FIVE, MINOR_NINE, MAJOR_NINE, ADD_NINE, SEVEN_SHARP_NINE, ELEVEN,
	MINOR_ELEVEN, THIRTEEN, MAJOR_THIRTEEN, SUSPEND_TWO, SUSPEND_FOUR,
	SEVEN_SUSPEND_FOUR, NINE_SUSPEND_FOUR, DIMINISHED, DIMINISHED_SEVEN, AUGMENTED
}
